version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - qdrant

  viz:
    build: 
      context: .
      dockerfile: src/logging/viz/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - api

volumes:
  qdrant_data: 